[package]
name = "run_on_filechange"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
nix = { version = "0.30.1", features = ["signal"] }
notify = "8.0.0"

[profile.release]
opt-level = 3
lto = true
